#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  2 17:04:09 2020

@author: chengeorge
"""
import numpy as np
import matplotlib.pyplot as plt
##r=np.roots([3,5,1])
##print(r)
##np.rint([1.4,1.5,1.6,2.5])
#x=np.linspace(0,10,20)
#y=np.sin(x)
#
#yp=np.linspace(0,10,100)
#yinterp=np.interp(yp,x,y)
#
#plt.plot(x,y,'o')
#plt.plot(yp,yinterp,'-x')
#plt.show

d1=np.random.randint(1,6+1,1000)
d2=np.random.randint(1,6+1,1000)
dsums=d1+d2
plt.hist(dsums,bins=5)
plt.show
